# Generated by Django 3.2.7 on 2021-09-07 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='guruh nomi')),
                ('mentor', models.CharField(max_length=40)),
                ('time', models.DateTimeField()),
                ('weekdays', models.CharField(max_length=200, verbose_name='hafta kunlari')),
                ('course_title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='telegram_bot.course')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_user', models.CharField(choices=[('AD', 'Admin'), ('ME', 'Mentor'), ('ST', 'Student')], default='ST', max_length=2)),
                ('user_id', models.IntegerField()),
                ('tg_username', models.CharField(max_length=20, verbose_name='Username')),
                ('name', models.CharField(max_length=20, verbose_name='Familya Ism')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('phone', models.CharField(max_length=12, unique=True)),
                ('gender', models.CharField(choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='telegram_bot.group')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
        ),
    ]
