# Generated by Django 3.2.7 on 2021-09-09 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_auto_20210907_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='step', to='telegram_bot.user')),
            ],
        ),
    ]
