# Generated by Django 3.2.7 on 2021-09-09 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0003_userstep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstep',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='step', to='telegram_bot.user', unique=True),
        ),
    ]
