# Generated by Django 3.2.7 on 2021-09-09 15:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0005_alter_userstep_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='price',
            field=models.IntegerField(default=500000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='technologies',
            field=models.CharField(default="kompyuter savodxonligi", max_length=200, verbose_name='texnologiyalar'),
            preserve_default=False,
        ),
    ]
